# Site
name: "HoangTu"
title: "HoangTu Blog"
description: "Wellcome to HoangTu blog"
meta_description: "Wellcome to HoangTu blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'https-nghti-github-io'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  nghti:
    name: nghti
    display_name: nghti
    gravatar: 817789f985a387521d6ec4d5a18137c1
    email: nghti8020@gmail.com
    web: nghti.github.io
    twitter: https://twitter.com/nghti8020
    description: "I'am developer"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
